import type { EmojiResolver } from '../types.js'
import { resolveEmojiImage } from '../utils/emojis.js'

// The pictogram names TypePad's set ships, as its WordPress plugin lists them.
// See: https://plugins.svn.wordpress.org/typepad-emoji-for-tinymce/trunk/icons/.
const pictogramNames = [
  '24hours',
  'airplane',
  'angry',
  'annoy',
  'apple',
  'appli01',
  'appli02',
  'aquarius',
  'aries',
  'art',
  'atm',
  'bag',
  'ban',
  'banana',
  'bank',
  'bar',
  'baseball',
  'basketball',
  'bearing',
  'beer',
  'bell',
  'bicycle',
  'birthday',
  'bleah',
  'bomb',
  'book',
  'bottle',
  'boutique',
  'bread',
  'bud',
  'building',
  'bullettrain',
  'bus',
  'by-d',
  'cafe',
  'cake',
  'camera',
  'cancer',
  'capricornus',
  'car',
  'carouselpony',
  'cat',
  'catface',
  'cd',
  'chair',
  'cherry',
  'cherryblossom',
  'chick',
  'clear',
  'clip',
  'clock',
  'cloud',
  'clover',
  'club',
  'coldsweats01',
  'coldsweats02',
  'confident',
  'copyright',
  'crown',
  'crying',
  'cute',
  'd-point',
  'danger',
  'dash',
  'delicious',
  'denim',
  'despair',
  'diamond',
  'dog',
  'dollar',
  'door',
  'down',
  'downwardleft',
  'downwardright',
  'drama',
  'ear',
  'eight',
  'empty',
  'end',
  'enter',
  'event',
  'eye',
  'eyeglass',
  'fastfood',
  'faxto',
  'fish',
  'five',
  'flag',
  'flair',
  'foot',
  'four',
  'free',
  'freedial',
  'fuji',
  'full',
  'fullmoon',
  'game',
  'gasstation',
  'gawk',
  'gemini',
  'golf',
  'good',
  'hairsalon',
  'happy01',
  'happy02',
  'heart',
  'heart01',
  'heart02',
  'heart03',
  'heart04',
  'horse',
  'hospital',
  'hotel',
  'house',
  'id',
  'impact',
  'info01',
  'info02',
  'japanesetea',
  'karaoke',
  'key',
  'kissmark',
  'leftright',
  'leo',
  'libra',
  'loveletter',
  'lovely',
  'mail',
  'mailto',
  'maple',
  'memo',
  'mist',
  'mobaq',
  'mobilephone',
  'moneybag',
  'moon1',
  'moon2',
  'moon3',
  'motorsports',
  'movie',
  'music',
  'new',
  'newmoon',
  'ng',
  'night',
  'nine',
  'noodle',
  'nosmoking',
  'note',
  'notes',
  'ok',
  'on',
  'one',
  'paper',
  'parking',
  'pass',
  'pc',
  'pen',
  'pencil',
  'penguin',
  'phoneto',
  'pig',
  'pisces',
  'pocketbell',
  'postoffice',
  'pouch',
  'pout',
  'present',
  'punch',
  'r-mark',
  'rain',
  'recycle',
  'restaurant',
  'ribbon',
  'riceball',
  'ring',
  'rock',
  'rouge',
  'run',
  'rvcar',
  'sad',
  'sagittarius',
  'sandclock',
  'school',
  'scissors',
  'scorpius',
  'search',
  'secret',
  'seven',
  'shadow',
  'sharp',
  'shine',
  'ship',
  'shock',
  'shoe',
  'sign01',
  'sign02',
  'sign03',
  'sign04',
  'sign05',
  'signaler',
  'six',
  'ski',
  'slate',
  'sleepy',
  'smile',
  'smoking',
  'snail',
  'snow',
  'snowboard',
  'soccer',
  'soon',
  'spa',
  'spade',
  'sports',
  'sprinkle',
  'subway',
  'sun',
  'sweat01',
  'sweat02',
  't-shirt',
  'taurus',
  'telephone',
  'tennis',
  'think',
  'three',
  'thunder',
  'ticket',
  'tm',
  'toilet',
  'train',
  'tulip',
  'tv',
  'two',
  'typhoon',
  'up',
  'updown',
  'upwardleft',
  'upwardright',
  'virgo',
  'watch',
  'wave',
  'weep',
  'wheelchair',
  'wine',
  'wink',
  'wobbly',
  'wrench',
  'xmas',
  'yacht',
  'yen',
  'zero',
]

// TypePad's uploaded asset, which names the pictogram only in a class beside `emoticon`.
const assetSelector = 'img[src*="/.a/" i][class~="emoticon"]'

// Cocolog's pictograms, named in English with no alt. They have no Unicode counterpart to become.
export const cocologEmojiResolver: EmojiResolver = {
  kind: 'emoji',
  selector: [
    'img[src*="emojies.cocolog-nifty.com/emoticon/" i]', // Cocolog
    'img[src*="/.shared/images/emoticon/" i]', // TypePad, which Cocolog runs on, from any of its hosts
    'img[src*="/wp-content/plugins/typepad-emoji-for-tinymce/icons/" i]', // TypePad's set in WordPress
    'img[src*="/plugins/EmoticonButton/images/emoticons/" i]', // The same set in Movable Type
    'img[src*="/plugins/MTEntryFlex/fckeditor/editor/images/smiley/typepad/" i]', // Movable Type
    assetSelector, // TypePad
  ].join(', '),
  extract: (element) => {
    // Any TypePad upload can carry the emoticon class, so only a pictogram name marks one.
    const hasPictogramName = pictogramNames.some((name) => element.classList.contains(name))

    if (element.matches(assetSelector) && !hasPictogramName) {
      return
    }

    return resolveEmojiImage(element, { isStrong: true })
  },
}
