import { toMap } from 'trousse'
import type { EmojiResolver } from '../types.js'
import { getFileStem, resolveEmojiImage } from '../utils/emojis.js'
import { glyphFromGemojiName } from '../utils/gemoji.js'

// The emoji sets a Discourse site can pick, each served from `/images/emoji/<set>/`. A custom
// emoji is an upload under `/uploads/` instead.
const sets = [
  'apple',
  'emoji_one',
  'facebook_messenger',
  'fluentui',
  'google',
  'google_classic',
  'noto',
  'twemoji',
  'twitter',
  'win10',
]

// Names Discourse draws as another glyph than gemoji.
// See: https://github.com/discourse/discourse-emojis/blob/29ebe49dee08fcb921e2530ed7718e3236f802a7/dist/emojis.json.
const discourseNames = toMap<string>({
  frowning: '☹️',
  kiss: '💏',
  couple_with_heart: '👩‍❤️‍👨',
  dog: '🐕',
  cat: '🐈',
  tiger: '🐅',
  horse: '🐎',
  cow: '🐄',
  pig: '🐖',
  camel: '🐪',
  mouse: '🐁',
  rabbit: '🐇',
  whale: '🐋',
  post_office: '🏤',
  train: '🚆',
  satellite: '🛰️',
  umbrella: '☂️',
  snowman: '☃️',
  sunglasses: '🕶️',
  pencil: '✏️',
  japan: '🇯🇵',
})

// Discourse's own aliases, each to the Discourse name it draws. An alias gemoji already draws the
// same is left out.
// See: https://github.com/discourse/discourse-emojis/blob/29ebe49dee08fcb921e2530ed7718e3236f802a7/dist/aliases.json.
const discourseAliases = toMap<string>({
  xray: 'x_ray',
  anger_right: 'right_anger_bubble',
  person_with_ball: 'person_bouncing_ball',
  basketball_player: 'person_bouncing_ball',
  bellhop: 'bellhop_bell',
  biohazard_sign: 'biohazard',
  archery: 'bow_and_arrow',
  calendar_spiral: 'spiral_calendar',
  spiral_calendar_pad: 'spiral_calendar',
  card_box: 'card_file_box',
  city_dusk: 'cityscape_at_dusk',
  couch: 'couch_and_lamp',
  lower_left_crayon: 'crayon',
  cricket_bat_and_ball: 'cricket_game',
  cricket_bat_ball: 'cricket_game',
  cross: 'latin_cross',
  dagger_knife: 'dagger',
  desktop: 'desktop_computer',
  dividers: 'card_index_dividers',
  dove_of_peace: 'dove',
  feet: 'footprints',
  flame: 'fire',
  flag_black: 'black_flag',
  waving_black_flag: 'black_flag',
  flag_white: 'white_flag',
  waving_white_flag: 'white_flag',
  frame_photo: 'framed_picture',
  frame_with_picture: 'framed_picture',
  hammer_pick: 'hammer_and_pick',
  homes: 'houses',
  house_buildings: 'houses',
  house_abandoned: 'derelict_house',
  derelict_house_building: 'derelict_house',
  island: 'desert_island',
  key2: 'old_key',
  lifter: 'person_lifting_weights',
  weight_lifter: 'person_lifting_weights',
  medal: 'sports_medal',
  reversed_hand_with_middle_finger_extended: 'fu',
  racing_motorcycle: 'motorcycle',
  notepad_spiral: 'spiral_notepad',
  spiral_note_pad: 'spiral_notepad',
  oil: 'oil_drum',
  grandma: 'old_woman',
  grandpa: 'old_man',
  lower_left_paintbrush: 'paintbrush',
  double_vertical_bar: 'pause_button',
  peace: 'peace_symbol',
  pen_fountain: 'fountain_pen',
  lower_left_fountain_pen: 'fountain_pen',
  table_tennis: 'ping_pong',
  worship_symbol: 'place_of_worship',
  poo: 'poop',
  radioactive_sign: 'radioactive',
  railroad_track: 'railway_track',
  robot_face: 'robot',
  skeleton: 'skull',
  skull_crossbones: 'skull_and_crossbones',
  speaking_head_in_silhouette: 'speaking_head',
  spy: 'man_detective',
  sleuth_or_spy: 'man_detective',
  thunder_cloud_rain: 'cloud_with_lightning_and_rain',
  thunder_cloud_and_rain: 'cloud_with_lightning_and_rain',
  track_next: 'next_track_button',
  next_track: 'next_track_button',
  unicorn_face: 'unicorn',
  urn: 'funeral_urn',
  white_sun_cloud: 'sun_behind_large_cloud',
  white_sun_behind_cloud: 'sun_behind_large_cloud',
  white_sun_rain_cloud: 'sun_behind_rain_cloud',
  white_sun_behind_cloud_with_rain: 'sun_behind_rain_cloud',
  white_sun_small_cloud: 'sun_behind_small_cloud',
  white_sun_with_small_cloud: 'sun_behind_small_cloud',
  umbrella2: 'umbrella',
  tools: 'hammer_and_wrench',
  thermometer_face: 'face_with_thermometer',
  timer: 'timer_clock',
  slightly_smiling: 'slightly_smiling_face',
  slight_smile: 'slightly_smiling_face',
  upside_down: 'upside_down_face',
  money_mouth: 'money_mouth_face',
  nerd: 'nerd_face',
  hugging: 'hugs',
  hugging_face: 'hugs',
  rolling_eyes: 'roll_eyes',
  slight_frown: 'slightly_frowning_face',
  frowning2: 'frowning',
  white_frowning_face: 'frowning',
  zipper_mouth: 'zipper_mouth_face',
  head_bandage: 'face_with_head_bandage',
  hand_splayed: 'hand_with_fingers_splayed',
  vulcan: 'vulcan_salute',
  raised_hand_with_part_between_middle_and_ring_fingers: 'vulcan_salute',
  policeman: 'police_officer',
  bow: 'man_bowing',
  cruise_ship: 'passenger_ship',
  motorboat: 'motor_boat',
  boat: 'motor_boat',
  airplane_arriving: 'airplane_arrival',
  airplane_small: 'small_airplane',
  race_car: 'racing_car',
  family_man_woman_boys: 'family_man_woman_boy_boy',
  family_man_woman_girls: 'family_man_woman_girl_girl',
  family_women_boy: 'family_woman_woman_boy',
  family_women_girl: 'family_woman_woman_girl',
  family_women_girl_boy: 'family_woman_woman_girl_boy',
  family_women_boys: 'family_woman_woman_boy_boy',
  family_women_girls: 'family_woman_woman_girl_girl',
  family_men_boy: 'family_man_man_boy',
  family_men_girl: 'family_man_man_girl',
  family_men_girl_boy: 'family_man_man_girl_boy',
  family_men_boys: 'family_man_man_boy_boy',
  family_men_girls: 'family_man_man_girl_girl',
  cloud_lightning: 'cloud_with_lightning',
  cloud_tornado: 'tornado',
  cloud_with_tornado: 'tornado',
  cloud_rain: 'cloud_with_rain',
  cloud_snow: 'cloud_with_snow',
  microphone2: 'studio_microphone',
  lion_face: 'lion',
  satellite_orbital: 'satellite',
  mouse_three_button: 'computer_mouse',
  three_button_mouse: 'computer_mouse',
  wind_blowing_face: 'wind_face',
  golfer: 'man_golfing',
  construction_site: 'building_construction',
  hockey: 'ice_hockey',
  play_pause: 'play_or_pause_button',
  projector: 'film_projector',
  park: 'national_park',
  map: 'world_map',
  pen_ballpoint: 'pen',
  lower_left_ballpoint_pen: 'pen',
  atom: 'atom_symbol',
  clock: 'mantelpiece_clock',
  scales: 'balance_scale',
  couplekiss: 'kiss_woman_man',
  female_couplekiss: 'kiss_woman_woman',
  male_couplekiss: 'kiss_man_man',
  male_couple_with_heart: 'couple_with_heart_man_man',
  female_couple_with_heart: 'couple_with_heart_woman_woman',
  compression: 'clamp',
  sleeping_accommodation: 'person_in_bed',
  om_symbol: 'om',
  rowing_boat: 'man_rowing_boat',
  rowboat: 'man_rowing_boat',
  moon: 'new_moon',
  'fleur-de-lis': 'fleur_de_lis',
  puke: 'face_vomiting',
  crazy_face: 'zany_face',
  relaxed: 'relieved_face',
  frowning_with_open_mouth: 'frowning_face_with_open_mouth',
  face_with_symbols_over_mouth: 'face_with_symbols_on_mouth',
  heavy_heart_exclamation_mark_ornament: 'heart_exclamation',
  high_five: 'folded_hands',
  hear_with_hearing_aid: 'ear_with_hearing_aid',
  person_with_blond_hair: 'person_blond_hair',
  man_red_haired: 'man_red_hair',
  man_curly_haired: 'man_curly_hair',
  man_white_haired: 'man_white_hair',
  woman_red_haired: 'woman_red_hair',
  woman_curly_haired: 'woman_curly_hair',
  woman_white_haired: 'woman_white_hair',
  old_person: 'older_person',
  person_with_pouting_face: 'person_pouting',
  guardsman: 'guard',
  bride_with_veil: 'person_with_veil',
  massage: 'woman_getting_massage',
  runner: 'man_running',
  dancing_women: 'people_with_bunny_ears',
  man_in_business_suit_levitating: 'person_in_suit_levitating',
  levitate: 'person_in_suit_levitating',
  swimmer: 'man_swimming',
  bicyclist: 'man_biking',
  mountain_bicyclist: 'man_mountain_biking',
  whale2: 'spouting_whale',
  maté: 'mate',
  sushing_face: 'shushing_face',
  fork_knife_plate: 'fork_and_knife_with_plate',
  parasol_on_ground: 'beach_with_umbrella',
  beach: 'beach_with_umbrella',
  ringer_planet: 'ringed_planet',
  snowman2: 'snowman_without_snow',
  red_gift_envelope: 'red_envelope',
  helmet_with_cross: 'rescue_worker_s_helmet',
  helmet_with_white_cross: 'rescue_worker_s_helmet',
  newspaper2: 'rolled_up_newspaper',
  calendar: 'date',
  roll_of_toilet_paper: 'roll_of_paper',
  track_previous: 'last_track_button',
  previous_track: 'last_track_button',
  keycap_hash: 'hash',
  'keycap_#': 'hash',
  keycap_asterisk: 'asterisk',
  'keycap_*': 'asterisk',
  keycap_star: 'asterisk',
  sa: 'japanese_not_free_of_charge_button',
  ceuta_and_melilla: 'ceuta_melilla',
  heard_and_mc_donald_islands: 'heard_mcdonald_islands',
  flag_jp: 'japan',
  svalbard_and_jan_mayen: 'svalbard_jan_mayen',
})

const queryOrHashRegex = /[?#]/
// A toned file is named by its Fitzpatrick type, 2 to 6, inside a folder named for the emoji.
const toneRegex = /^[2-6]$/
const firstModifier = 0x1f3fb // U+1F3FB, Fitzpatrick type 1-2

const getNameGlyph = (name: string): string | undefined => {
  return discourseNames.get(name) ?? glyphFromGemojiName(name)
}

// See: https://github.com/discourse/discourse/blob/main/app/models/emoji.rb, for the tone.
const getGlyph = (src: string): string | undefined => {
  const path = src.split(queryOrHashRegex)[0]
  const stem = getFileStem(path)
  const isToned = toneRegex.test(stem)
  const name = isToned ? getFileStem(path.slice(0, path.lastIndexOf('/'))) : stem
  const glyph = getNameGlyph(discourseAliases.get(name) ?? name)

  if (!glyph || !isToned) {
    return glyph
  }

  // The modifier follows the first codepoint and replaces a variation selector there.
  const [first, ...rest] = [...glyph]
  const tail = rest[0] === '️' ? rest.slice(1) : rest
  const modifier = String.fromCodePoint(firstModifier + Number(stem) - 2)

  return [first, modifier, ...tail].join('')
}

// Discourse's stock emoji, named by the shortcode Discourse writes, a gemoji name or its own.
export const discourseEmojiResolver: EmojiResolver = {
  kind: 'emoji',
  selector: sets.map((set) => `img[class~="emoji" i][src*="/images/emoji/${set}/" i]`).join(', '),
  extract: (element) => {
    const glyph = getGlyph(element.getAttribute('src') ?? '')

    return resolveEmojiImage(element, { isStrong: true, glyph })
  },
}
