import { toMap } from 'trousse'
import type { EmojiResolver } from '../types.js'
import { type EmojiGlyph, resolveEmojiImage } from '../utils/emojis.js'

// The Kolobok set, which PunBB and FluxBB packs, QIP, vBulletin's AMD pack, Drupal and many uCoz
// boards ship. Its two-letter names say nothing of the drawing.
export const kolobokEmojiNames = toMap<EmojiGlyph>({
  aa: false,
  ab: false,
  ac: false,
  ad: false,
  ae: false,
  af: false,
  ag: false,
  ah: false,
  ai: false,
  aj: false,
  ak: false,
  al: false,
  am: false,
  an: false,
  ao: false,
  ap: false,
  aq: false,
  ar: false,
  as: false,
  at: false,
  au: false,
  av: false,
  aw: false,
  ax: false,
  ay: false,
  az: false,
  ba: false,
  bb: false,
  bc: false,
  bd: false,
  be: false,
  bf: false,
  bg: false,
  bh: false,
  bi: false,
  bj: false,
  bk: false,
  bl: false,
  bm: false,
  bn: false,
  bo: false,
  bp: false,
  bq: false,
  br: false,
  bs: false,
  bt: false,
  bu: false,
  bv: false,
  bw: false,
  by: false,
  bz: false,
  ca: false,
  cb: false,
  cc: false,
  cd: false,
  ce: false,
  cj: false,
  ck: false,
  cl: false,
  cn: false,
  cq: false,
  cs: false,
  cv: false,
  cw: false,
  cx: false,
  cy: false,
  cz: false,
  da: false,
  db: false,
  dc: false,
  de: false,
  dg: false,
  dh: false,
  di: false,
  dj: false,
  dk: false,
  dm: false,
  dp: false,
  dx: false,
  ea: false,
  eb: false,
  ec: false,
  ee: false,
  ef: false,
  ej: false,
  el: false,
  en: false,
  es: false,
  eu: false,
})

// Smilies hotlinked from kolobok.us, the set's own gallery, named like `standart/pardon.gif`. Every
// file there is a Kolobok drawing, so the host alone marks it.
export const kolobokEmojiResolver: EmojiResolver = {
  kind: 'emoji',
  selector: [
    'img[src*="kolobok.us/smiles/" i]',
    'img[src*="smiles.kolobok.us/" i]',
    'img[src*="kolobok.us/content_images/emotes/" i]',
  ].join(','),
  extract: (element) => {
    return resolveEmojiImage(element, { isStrong: true, names: kolobokEmojiNames })
  },
}
