import { toMap } from 'trousse'
import type { EmojiResolver } from '../types.js'
import { type EmojiGlyph, resolveEmojiImage } from '../utils/emojis.js'

// Open Live Writer's emoticon ids, every one drawn as its own MSN-style face. `inlove` is
// Windows Live Writer's, absent from Open Live Writer.
// See: https://github.com/OpenLiveWriter/OpenLiveWriter/blob/master/src/managed/OpenLiveWriter.PostEditor/Emoticons/EmoticonsManager.cs.
const liveWriterEmojiNames = toMap<EmojiGlyph>({
  smile: false,
  openmouthedsmile: false,
  winkingsmile: false,
  surprisedsmile: false,
  smilewithtongueout: false,
  hotsmile: false,
  angrysmile: false,
  embarrassedsmile: false,
  confusedsmile: false,
  sadsmile: false,
  cryingface: false,
  disappointedsmile: false,
  devil: false,
  angel: false,
  vampirebat: false,
  donttellanyonesmile: false,
  baringteethsmile: false,
  nerdsmile: false,
  sarcasticsmile: false,
  secrettellingsmile: false,
  sicksmile: false,
  berightback: false,
  idontknowsmile: false,
  thinkingsmile: false,
  partysmile: false,
  eyerollingsmile: false,
  sleepysmile: false,
  shifty: false,
  annoyed: false,
  justkidding: false,
  ninja: false,
  greenwithenvy: false,
  laughingoutloud: false,
  rollingonthefloorlaughing: false,
  nyahnyah: false,
  alien: false,
  flirtfemale: false,
  flirtmale: false,
  freezing: false,
  princess: false,
  ghost: false,
  punch: false,
  punk: false,
  steamingmad: false,
  whome: false,
  sendakiss: false,
  redheart: false,
  brokenheart: false,
  catface: false,
  dogface: false,
  sleepinghalfmoon: false,
  star: false,
  filmstrip: false,
  note: false,
  email: false,
  redrose: false,
  wiltedrose: false,
  clock: false,
  redlips: false,
  giftwithabow: false,
  birthdaycake: false,
  camera: false,
  lightbulb: false,
  coffeecup: false,
  callme: false,
  lefthug: false,
  righthug: false,
  mug: false,
  martiniglass: false,
  boy: false,
  girl: false,
  thumbsup: false,
  thumbsdown: false,
  goat: false,
  sun: false,
  rainbow: false,
  snail: false,
  turtle: false,
  plate: false,
  bowl: false,
  pizza: false,
  soccerball: false,
  auto: false,
  airplane: false,
  umbrella: false,
  islandwithapalmtree: false,
  computer: false,
  mobilephone: false,
  stormcloud: false,
  pointingup: false,
  highfive: false,
  fingerscrossed: false,
  money: false,
  blacksheep: false,
  lightning: false,
  work: false,
  bunny: false,
  schoolbus: false,
  peace: false,
  school: false,
  inlove: false,
})

// Live Writer's emoticons, uploaded with the post as ordinary images. The alt is the localized
// name, and blogs that re-upload the file drop the class but keep `wlEmoticon` in its name.
export const liveWriterEmojiResolver: EmojiResolver = {
  kind: 'emoji',
  selector: 'img[class~="wlEmoticon"], img[src*="wlemoticon" i]',
  extract: (element) => {
    return resolveEmojiImage(element, { isStrong: true, names: liveWriterEmojiNames })
  },
}
